volumes:
    bloom-postgres-data:
    bloom-redis-data:

x-app-base: &app-base
    build:
        context: ./app
    env_file:
        - .env
    environment:
        - PYTHONPATH=/app
    volumes:
        - ${DEV_MOUNT:-./app}:/app:z
    networks:
        - default

services:
    postgres:
        container_name: bloom_postgres-16
        image: postgres:16-alpine
        restart: always
        networks:
            - default
        ports:
            - "5432:5432"
        env_file:
            - .env
        environment:
            - PGDATA=/var/lib/postgresql/data/pgdata
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
            - POSTGRES_USER=${POSTGRES_USER:-postgres}
            - POSTGRES_DB=${POSTGRES_DB:-bloom_db_dev}
        volumes:
            - bloom-postgres-data:/var/lib/postgresql/data/pgdata
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres -d bloom_db_dev"]
            interval: 10s
            timeout: 5s
            retries: 5

    redis:
        container_name: bloom_redis-7
        image: redis:7-alpine
        networks:
            - default
        volumes:
            - bloom-redis-data:/data
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 10s
            timeout: 3s
            retries: 5

    app:
        <<: *app-base
        container_name: bloom_api-1
        expose:
            - "3000"
        command: sh -c "chmod +x ./scripts/dev.sh && ./scripts/dev.sh"
        depends_on:
            postgres:
                condition: service_healthy
            redis:
                condition: service_healthy
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "curl -f http://localhost:3000/health/ || curl -f http://localhost:3000/health",
                ]
            interval: 1m30s
            timeout: 30s
            retries: 5
            start_period: 30s

    nginx:
        container_name: bloom_nginx-1
        image: nginx:alpine
        ports:
            - "3000:80"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro,Z
        depends_on:
            app:
                condition: service_healthy
        networks:
            - default
        healthcheck:
            test:
                [
                    "CMD",
                    "wget",
                    "--quiet",
                    "--tries=1",
                    "--spider",
                    "http://localhost/health",
                ]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 30s

    celery_worker:
        <<: *app-base
        container_name: bloom_celery-worker-1
        command: celery -A src.core.celery worker -Q bloom_default_tasks,bloom_recurring_tasks -l INFO
        depends_on:
            app:
                condition: service_healthy
            redis:
                condition: service_healthy

    celery_beat:
        <<: *app-base
        container_name: bloom_celery-beat-1
        command: celery -A src.core.celery beat -l INFO
        depends_on:
            app:
                condition: service_healthy
            redis:
                condition: service_healthy

    mailcatcher:
        container_name: bloom_mailcatcher-1
        image: schickling/mailcatcher
        ports:
            - "1080:1080"
            - "1025:1025"
