version: 1
disable_existing_loggers: false

formatters:
  json_formatter:
    (): src.core.logging.formatters.StructuredExceptionJsonFormatter
    format: "%(asctime)s %(name)s %(levelname)s %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
    rename_fields:
      levelname: level
      asctime: timestamp
      name: logger

filters:
  context_filter:
    (): src.core.logging.filters.CombinedContextFilter

  noise_reduction:
    (): src.core.logging.filters.NoiseReductionFilter
    suppress_patterns: ["/health", "/metrics", "/ping"]

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: json_formatter
    filters: [context_filter, noise_reduction]
    stream: ext://sys.stdout

  error_file:
    class: logging.FileHandler
    level: ERROR
    formatter: json_formatter
    filters: [context_filter]
    filename: logs/errors.log

loggers:
  src:
    level: DEBUG
    handlers: [console, error_file]
    propagate: false

  uvicorn.access:
    level: WARNING
    propagate: false

  sqlalchemy.engine:
    level: INFO
    propagate: true

root:
  level: WARNING
  handlers: [console]
