"""update_product_item_and_order_table

Revision ID: 0c0951e5905b
Revises: 7db4b9f07219
Create Date: 2025-11-12 08:55:03.025570

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0c0951e5905b"
down_revision: Union[str, Sequence[str], None] = "7db4b9f07219"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("order_invoices", sa.Column("friendly_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column("order_invoices", sa.Column("friendly_slug", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column(
        "order_invoices", sa.Column("invoice_tag", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False)
    )
    op.add_column("order_invoices", sa.Column("subtotal", sa.NUMERIC(precision=12, scale=2), nullable=False))
    op.add_column("order_invoices", sa.Column("tax_amount", sa.NUMERIC(precision=12, scale=2), nullable=False))
    op.add_column("order_invoices", sa.Column("discount_amount", sa.NUMERIC(precision=12, scale=2), nullable=False))
    op.add_column("order_invoices", sa.Column("total_amount", sa.NUMERIC(precision=12, scale=2), nullable=False))
    op.add_column("order_invoices", sa.Column("amount_paid", sa.NUMERIC(precision=12, scale=2), nullable=False))
    op.add_column("order_invoices", sa.Column("currency", sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False))
    op.add_column(
        "order_invoices",
        sa.Column("issue_date", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
    )
    op.add_column("order_invoices", sa.Column("paid_date", sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column("order_invoices", sa.Column("notes", sa.TEXT(), nullable=True))
    op.add_column(
        "order_invoices", sa.Column("billing_name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False)
    )
    op.add_column(
        "order_invoices", sa.Column("billing_email", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False)
    )
    op.add_column(
        "order_invoices", sa.Column("billing_phone", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True)
    )
    op.add_column("order_invoices", sa.Column("billing_address", sa.TEXT(), nullable=True))
    op.drop_index(op.f("ix_order_invoices_invoiceable_id"), table_name="order_invoices")
    op.drop_index(op.f("ix_order_invoices_invoiceable_type"), table_name="order_invoices")
    op.drop_index(op.f("ix_order_invoices_order_id"), table_name="order_invoices")
    op.create_index(op.f("ix_order_invoices_order_id"), "order_invoices", ["order_id"], unique=True)
    op.create_index(op.f("ix_order_invoices_friendly_id"), "order_invoices", ["friendly_id"], unique=True)
    op.create_index(op.f("ix_order_invoices_friendly_slug"), "order_invoices", ["friendly_slug"], unique=True)
    op.create_index(op.f("ix_order_invoices_invoice_tag"), "order_invoices", ["invoice_tag"], unique=True)
    op.drop_column("order_invoices", "amount")
    op.drop_column("order_invoices", "invoiceable_id")
    op.drop_column("order_invoices", "invoiceable_type")
    op.add_column("order_items", sa.Column("unit_price", sa.NUMERIC(precision=12, scale=2), nullable=False))
    op.add_column("order_items", sa.Column("subtotal", sa.NUMERIC(precision=12, scale=2), nullable=False))
    op.add_column("order_items", sa.Column("tax_rate", sa.NUMERIC(precision=5, scale=2), nullable=False))
    op.add_column("order_items", sa.Column("tax_amount", sa.NUMERIC(precision=12, scale=2), nullable=False))
    op.add_column("order_items", sa.Column("discount_rate", sa.NUMERIC(precision=5, scale=2), nullable=False))
    op.add_column("order_items", sa.Column("discount_amount", sa.NUMERIC(precision=12, scale=2), nullable=False))
    op.add_column("order_items", sa.Column("total", sa.NUMERIC(precision=12, scale=2), nullable=False))
    op.drop_column("order_items", "price")
    op.drop_column("order_items", "updated_datetime")
    op.add_column("orders", sa.Column("order_tag", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    op.alter_column("orders", "session_id", existing_type=sa.VARCHAR(length=255), nullable=False)
    op.drop_index(op.f("ix_orders_session_id"), table_name="orders")
    op.create_index(op.f("ix_orders_session_id"), "orders", ["session_id"], unique=True)
    op.create_index(op.f("ix_orders_order_tag"), "orders", ["order_tag"], unique=True)
    op.alter_column("product_items", "product_id", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_constraint(op.f("uq_product_item_seller"), "product_items", type_="unique")
    op.create_index(
        "uq_product_item_seller",
        "product_items",
        ["product_id", "seller_account_id"],
        unique=True,
        postgresql_where="product_id IS NOT NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_product_item_seller", table_name="product_items", postgresql_where="product_id IS NOT NULL")
    op.create_unique_constraint(
        op.f("uq_product_item_seller"),
        "product_items",
        ["product_id", "seller_account_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column("product_items", "product_id", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_index(op.f("ix_orders_order_tag"), table_name="orders")
    op.drop_index(op.f("ix_orders_session_id"), table_name="orders")
    op.create_index(op.f("ix_orders_session_id"), "orders", ["session_id"], unique=False)
    op.alter_column("orders", "session_id", existing_type=sa.VARCHAR(length=255), nullable=True)
    op.drop_column("orders", "order_tag")
    op.add_column(
        "order_items",
        sa.Column("updated_datetime", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    )
    op.add_column(
        "order_items", sa.Column("price", sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False)
    )
    op.drop_column("order_items", "total")
    op.drop_column("order_items", "discount_amount")
    op.drop_column("order_items", "discount_rate")
    op.drop_column("order_items", "tax_amount")
    op.drop_column("order_items", "tax_rate")
    op.drop_column("order_items", "subtotal")
    op.drop_column("order_items", "unit_price")
    op.add_column(
        "order_invoices", sa.Column("invoiceable_type", sa.VARCHAR(length=120), autoincrement=False, nullable=True)
    )
    op.add_column("order_invoices", sa.Column("invoiceable_id", sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column(
        "order_invoices", sa.Column("amount", sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False)
    )
    op.drop_index(op.f("ix_order_invoices_invoice_tag"), table_name="order_invoices")
    op.drop_index(op.f("ix_order_invoices_friendly_slug"), table_name="order_invoices")
    op.drop_index(op.f("ix_order_invoices_friendly_id"), table_name="order_invoices")
    op.drop_index(op.f("ix_order_invoices_order_id"), table_name="order_invoices")
    op.create_index(op.f("ix_order_invoices_order_id"), "order_invoices", ["order_id"], unique=False)
    op.create_index(op.f("ix_order_invoices_invoiceable_type"), "order_invoices", ["invoiceable_type"], unique=False)
    op.create_index(op.f("ix_order_invoices_invoiceable_id"), "order_invoices", ["invoiceable_id"], unique=False)
    op.drop_column("order_invoices", "billing_address")
    op.drop_column("order_invoices", "billing_phone")
    op.drop_column("order_invoices", "billing_email")
    op.drop_column("order_invoices", "billing_name")
    op.drop_column("order_invoices", "notes")
    op.drop_column("order_invoices", "paid_date")
    op.drop_column("order_invoices", "issue_date")
    op.drop_column("order_invoices", "currency")
    op.drop_column("order_invoices", "amount_paid")
    op.drop_column("order_invoices", "total_amount")
    op.drop_column("order_invoices", "discount_amount")
    op.drop_column("order_invoices", "tax_amount")
    op.drop_column("order_invoices", "subtotal")
    op.drop_column("order_invoices", "invoice_tag")
    op.drop_column("order_invoices", "friendly_slug")
    op.drop_column("order_invoices", "friendly_id")
    # ### end Alembic commands ###
