"""add_attachment_to_account_type_info

Revision ID: cb8d906380bd
Revises: b0ac1f81274b
Create Date: 2025-09-12 14:53:47.886307

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cb8d906380bd"
down_revision: Union[str, Sequence[str], None] = "b0ac1f81274b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("account_type_infos", sa.Column("attachment_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f("ix_account_type_infos_attachment_id"), "account_type_infos", ["attachment_id"], unique=False)
    op.create_foreign_key(None, "account_type_infos", "attachments", ["attachment_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "account_type_infos", type_="foreignkey")
    op.drop_index(op.f("ix_account_type_infos_attachment_id"), table_name="account_type_infos")
    op.drop_column("account_type_infos", "attachment_id")
    # ### end Alembic commands ###
